[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trinidi-data"
version = "0.1.0"
description = "Data files for trinidi"
dependencies = []

[tool.setuptools.package-data]
"trinidi_data" = ["*.npy"]